services:
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    container_name: mosquitto
    restart: on-failure
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./logs:/mosquitto/log
      - mosquitto-data:/mosquitto/data
    networks:
      - pubsub
networks:
  pubsub:
    driver: bridge
volumes:
  mosquitto-data:
    driver: local
